language: php
php:
- "7.2"
- "7.1"
- "7.0"
- "5.6"

install:
- php -i
- composer install

script:
- vendor/bin/phpunit

jobs:
  include:
    - stage: documentation
      if: branch = master
      install: skip
      script: "curl https://opensource.byjg.com/add-doc.sh | bash /dev/stdin php anydataset-sparql"
